export const ADD_QUESTION = 'ADD_QUESTION';
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const QUESTION_ANSWER = 'QUESTION_ANSWER';
export const FETCH_USERS = 'FETCH_USERS';
export const SET_AUTHED_USER = 'SET_AUTHED_USER';
